name: Purge jsDelivr Cache on new commit

on:
  push:
    branches:
      - main
    paths:
      - 'index.css'

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr Cache on new commit
        run: |
          curl "https://purge.jsdelivr.net/gh/Mub1532/emby-horizontal-livetv-cards-css@main/index.css"
